services:
  postgres:
    image: postgres:16
    container_name: tfm-postgres
    environment:
      POSTGRES_USER: om_demo
      POSTGRES_PASSWORD: om_demo
      POSTGRES_DB: opendata_demo
    ports:
      - "5432:5432"
    volumes:
      - ./sql/opendata_demo_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro

